In [27]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

# 1.문제정의
- 컬럼을 사용해서 강아지 예측하기

# 2. 데이터 수집

In [28]:
dogData=pd.read_csv('dogComp1.csv',encoding='euc-kr')

In [30]:
dogData.head()

,Unnamed: 0,이름,친화성,털빠짐,집지키기,실내외구분,운동량,체고,체중,크기,거주조건,나이조건
0,0,프렌치 불도그 [French Bulldog],m,h,f,io,m,28,11.5,M,ADJ,ALL
1,1,풍산개 [Poongsan Dog],l,m,h,o,m,54,25.5,M,DJ,YO
2,2,풀리 [Puli],m,l,h,o,h,40,13.5,M,DJ,ALL
3,3,포인터 [Pointer],h,m,f,o,h,63,26.5,L,DJ,YO
4,4,포메라니안 [Pomeranian],m,m,h,i,m,28,2.3,S,ADJ,ALL

# 3. 데이터 전처리

In [31]:
#Unnamed 컬럼이름 바꾸기
dogData.rename(columns={
    dogData.columns[0]:'정답'
},inplace=True)

In [33]:
dogData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 127 entries, 0 to 126
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   정답      127 non-null    int64
 1   이름      127 non-null    object
 2   친화성     127 non-null    object
 3   털빠짐     127 non-null    object
 4   집지키기    127 non-null    object
 5   실내외구분   127 non-null    object
 6   운동량     127 non-null    object
 7   체고      127 non-null    int64
 8   체중      127 non-null    float64
 9   크기      127 non-null    object
 10  거주조건    127 non-null    object
 11  나이조건    127 non-null    object
dtypes: float64(1), int64(2), object(9)
memory usage: 12.0+ KB

In [35]:
dogData.head()

   정답                        이름 친화성 털빠짐 집지키기 실내외구분 운동량  체고    체중 크기 거주조건 나이조건
0   0  프렌치 불도그 [French Bulldog]   m   h    f    io   m  28  11.5  M  ADJ  ALL
1   1        풍산개 [Poongsan Dog]   l   m    h     o   m  54  25.5  M   DJ   YO
2   2                 풀리 [Puli]   m   l    h     o   h  40  13.5  M   DJ  ALL
3   3             포인터 [Pointer]   h   m    f     o   h  63  26.5  L   DJ   YO
4   4        포메라니안 [Pomeranian]   m   m    h     i   m  28   2.3  S  ADJ  ALL

In [ ]:
#원 핫 인코딩

In [36]:
onehot_columns=['친화성','털빠짐','집지키기','실내외구분','운동량','크기','거주조건','나이조건']

In [39]:
for col in onehot_columns:
    dummy = pd.get_dummies(dogData[col],prefix=col)
    dogData = pd.concat([dogData,dummy],axis=1)
    dogData.drop(col,axis=1,inplace=True)

In [40]:
dogData

,정답,이름,체고,체중,친화성_h,친화성_l,친화성_m,털빠짐_h,털빠짐_l,털빠짐_m,...,크기_S,크기_XL,크기_XS,거주조건_A,거주조건_ADJ,거주조건_D,거주조건_DJ,나이조건_ALL,나이조건_Y,나이조건_YO
0,0,프렌치 불도그 [French Bulldog],28,11.5,0,0,1,1,0,0,...,0,0,0,0,1,0,0,1,0,0
1,1,풍산개 [Poongsan Dog],54,25.5,0,1,0,0,0,1,...,0,0,0,0,0,0,1,0,0,1
2,2,풀리 [Puli],40,13.5,0,0,1,0,1,0,...,0,0,0,0,0,0,1,1,0,0
3,3,포인터 [Pointer],63,26.5,1,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,1
4,4,포메라니안 [Pomeranian],28,2.3,0,0,1,0,0,1,...,1,0,0,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122,122,골든 리트리버 [Golden Retriever],56,31.5,1,0,0,1,0,0,...,0,0,0,0,0,1,0,1,0,0
123,123,휘펫 [Whippet],51,13.0,1,0,0,0,0,1,...,0,0,0,0,1,0,0,1,0,0
124,124,핏불 테리어 [America Pit Bull Terrier],51,29.5,1,0,0,0,0,1,...,0,0,0,0,1,0,0,0,1,0
125,125,필드 스파니엘 [Field Spaniel],46,19.0,0,0,1,0,0,1,...,0,0,0,0,0,0,1,1,0,0
126,126,플랫 코티드 리트리버 [Flat Coated Retriever],59,29.5,1,0,0,1,0,0,...,0,0,0,0,0,0,1,1,0,0

In [41]:
#체고와 체중은 크기로 구분할 수 있기때문에 컬럼을 삭제하겠다.
dogData.drop('체고',axis=1,inplace=True)
dogData.drop('체중',axis=1,inplace=True)

In [42]:
dogData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 127 entries, 0 to 126
Data columns (total 29 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   정답        127 non-null    int64
 1   이름        127 non-null    object
 2   친화성_h     127 non-null    uint8
 3   친화성_l     127 non-null    uint8
 4   친화성_m     127 non-null    uint8
 5   털빠짐_h     127 non-null    uint8
 6   털빠짐_l     127 non-null    uint8
 7   털빠짐_m     127 non-null    uint8
 8   집지키기_f    127 non-null    uint8
 9   집지키기_h    127 non-null    uint8
 10  집지키기_m    127 non-null    uint8
 11  실내외구분_i   127 non-null    uint8
 12  실내외구분_io  127 non-null    uint8
 13  실내외구분_o   127 non-null    uint8
 14  운동량_h     127 non-null    uint8
 15  운동량_l     127 non-null    uint8
 16  운동량_m     127 non-null    uint8
 17  크기_L      127 non-null    uint8
 18  크기_M      127 non-null    uint8
 19  크기_S      127 non-null    uint8
 20  크기_XL     127 non-null    uint8
 21  크기_XS     127 non-null    uint8
 22  거주조건_A    127 non-null    uint8
 23  거주조건_ADJ  127 non-null    uint8
 24  거주조건_D    127 non-null    uint8
 25  거주조건_DJ   127 non-null    uint8
 26  나이조건_ALL  127 non-null    uint8
 27  나이조건_Y    127 non-null    uint8
 28  나이조건_YO   127 non-null    uint8
dtypes: int64(1), object(1), uint8(27)
memory usage: 5.5+ KB

In [45]:
dogData.loc[:,'친화성_h':]

,친화성_h,친화성_l,친화성_m,털빠짐_h,털빠짐_l,털빠짐_m,집지키기_f,집지키기_h,집지키기_m,실내외구분_i,...,크기_S,크기_XL,크기_XS,거주조건_A,거주조건_ADJ,거주조건_D,거주조건_DJ,나이조건_ALL,나이조건_Y,나이조건_YO
0,0,0,1,1,0,0,1,0,0,0,...,0,0,0,0,1,0,0,1,0,0
1,0,1,0,0,0,1,0,1,0,0,...,0,0,0,0,0,0,1,0,0,1
2,0,0,1,0,1,0,0,1,0,0,...,0,0,0,0,0,0,1,1,0,0
3,1,0,0,0,0,1,1,0,0,0,...,0,0,0,0,0,0,1,0,0,1
4,0,0,1,0,0,1,0,1,0,1,...,1,0,0,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122,1,0,0,1,0,0,1,0,0,0,...,0,0,0,0,0,1,0,1,0,0
123,1,0,0,0,0,1,1,0,0,0,...,0,0,0,0,1,0,0,1,0,0
124,1,0,0,0,0,1,0,0,1,0,...,0,0,0,0,1,0,0,0,1,0
125,0,0,1,0,0,1,1,0,0,0,...,0,0,0,0,0,0,1,1,0,0
126,1,0,0,1,0,0,0,0,1,0,...,0,0,0,0,0,0,1,1,0,0

In [50]:
dogData.loc[:,'친화성_h']

0      0
1      0
2      0
3      1
4      0
      ..
122    1
123    1
124    1
125    0
126    1
Name: 친화성_h, Length: 127, dtype: uint8

In [51]:
#문제와 정답으로 분리
y=dogData['정답']
X=dogData.loc[:,'친화성_h':]

In [56]:
X_train,X_test,y_train,y_test = train_test_split(X,y,
                                                test_size=0.3,
                                                random_state=3)

In [57]:
logi = LogisticRegression()
logi.fit(X_train,y_train)
print("train score: ",logi.score(X_train,y_train))
print("test score: ",logi.score(X_test,y_test))

train score:  0.8863636363636364
test score:  0.0